theme: jekyll-theme-hacker
<<<<<<< HEAD
title: [someone will remember us, i say, even in another time]
description: [part-time philosopher, full-time faggot.]
=======

>>>>>>> c66deec73f307f64340d6ae1cdf735c0332c68eb
